# Generated by Django 5.1 on 2024-09-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_iser',
            new_name='id_user',
        ),
    ]
